/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.facebook.category

import com.vanniktech.emoji.facebook.FacebookEmoji
import de.cketti.codepoints.CodePoints

internal object SmileysAndPeopleCategoryChunk1 {
  internal val EMOJIS: List<FacebookEmoji> = listOf(
    FacebookEmoji(CodePoints.toString(0x1F621), listOf("rage"), 33, 17),
    FacebookEmoji(CodePoints.toString(0x1F620), listOf("angry"), 33, 16),
    FacebookEmoji(CodePoints.toString(0x1F92C), listOf("face_with_symbols_on_mouth", "serious_face_with_symbols_covering_mouth"), 41, 18),
    FacebookEmoji(CodePoints.toString(0x1F608), listOf("smiling_imp"), 32, 54),
    FacebookEmoji(CodePoints.toString(0x1F47F), listOf("imp"), 25, 41),
    FacebookEmoji(CodePoints.toString(0x1F480), listOf("skull"), 25, 42),
    FacebookEmoji(
      unicode = CodePoints.toString(0x2620),
      shortcodes = listOf("skull_and_crossbones"),
      x = 58,
      y = 24,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x2620, 0xFE0F), emptyList(), 58, 24),
      ),
    ),
    FacebookEmoji(CodePoints.toString(0x1F4A9), listOf("hankey", "poop", "shit"), 28, 25),
    FacebookEmoji(CodePoints.toString(0x1F921), listOf("clown_face"), 40, 52),
    FacebookEmoji(CodePoints.toString(0x1F479), listOf("japanese_ogre"), 25, 30),
    FacebookEmoji(CodePoints.toString(0x1F47A), listOf("japanese_goblin"), 25, 31),
    FacebookEmoji(CodePoints.toString(0x1F47B), listOf("ghost"), 25, 32),
    FacebookEmoji(CodePoints.toString(0x1F47D), listOf("alien"), 25, 39),
    FacebookEmoji(CodePoints.toString(0x1F47E), listOf("space_invader"), 25, 40),
    FacebookEmoji(CodePoints.toString(0x1F916), listOf("robot_face"), 39, 43),
    FacebookEmoji(CodePoints.toString(0x1F63A), listOf("smiley_cat"), 33, 45),
    FacebookEmoji(CodePoints.toString(0x1F638), listOf("smile_cat"), 33, 43),
    FacebookEmoji(CodePoints.toString(0x1F639), listOf("joy_cat"), 33, 44),
    FacebookEmoji(CodePoints.toString(0x1F63B), listOf("heart_eyes_cat"), 33, 46),
    FacebookEmoji(CodePoints.toString(0x1F63C), listOf("smirk_cat"), 33, 47),
    FacebookEmoji(CodePoints.toString(0x1F63D), listOf("kissing_cat"), 33, 48),
    FacebookEmoji(CodePoints.toString(0x1F640), listOf("scream_cat"), 33, 51),
    FacebookEmoji(CodePoints.toString(0x1F63F), listOf("crying_cat_face"), 33, 50),
    FacebookEmoji(CodePoints.toString(0x1F63E), listOf("pouting_cat"), 33, 49),
    FacebookEmoji(CodePoints.toString(0x1F648), listOf("see_no_evil"), 34, 50),
    FacebookEmoji(CodePoints.toString(0x1F649), listOf("hear_no_evil"), 34, 51),
    FacebookEmoji(CodePoints.toString(0x1F64A), listOf("speak_no_evil"), 34, 52),
    FacebookEmoji(CodePoints.toString(0x1F48C), listOf("love_letter"), 27, 8),
    FacebookEmoji(CodePoints.toString(0x1F498), listOf("cupid"), 28, 8),
    FacebookEmoji(CodePoints.toString(0x1F49D), listOf("gift_heart"), 28, 13),
    FacebookEmoji(CodePoints.toString(0x1F496), listOf("sparkling_heart"), 28, 6),
    FacebookEmoji(CodePoints.toString(0x1F497), listOf("heartpulse"), 28, 7),
    FacebookEmoji(CodePoints.toString(0x1F493), listOf("heartbeat"), 28, 3),
    FacebookEmoji(CodePoints.toString(0x1F49E), listOf("revolving_hearts"), 28, 14),
    FacebookEmoji(CodePoints.toString(0x1F495), listOf("two_hearts"), 28, 5),
    FacebookEmoji(CodePoints.toString(0x1F49F), listOf("heart_decoration"), 28, 15),
    FacebookEmoji(
      unicode = CodePoints.toString(0x2763),
      shortcodes = listOf("heavy_heart_exclamation_mark_ornament"),
      x = 60,
      y = 35,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x2763, 0xFE0F), emptyList(), 60, 35),
      ),
    ),
    FacebookEmoji(CodePoints.toString(0x1F494), listOf("broken_heart"), 28, 4),
    FacebookEmoji(
      unicode = CodePoints.toString(0x2764, 0x200D, 0x1F525),
      shortcodes = listOf("heart_on_fire"),
      x = 60,
      y = 36,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x2764, 0xFE0F, 0x200D, 0x1F525), emptyList(), 60, 36),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x2764, 0x200D, 0x1FA79),
      shortcodes = listOf("mending_heart"),
      x = 60,
      y = 37,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x2764, 0xFE0F, 0x200D, 0x1FA79), emptyList(), 60, 37),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x2764),
      shortcodes = listOf("heart"),
      x = 60,
      y = 38,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x2764, 0xFE0F), emptyList(), 60, 38),
      ),
    ),
    FacebookEmoji(CodePoints.toString(0x1FA77), listOf("pink_heart"), 54, 57),
    FacebookEmoji(CodePoints.toString(0x1F9E1), listOf("orange_heart"), 54, 19),
    FacebookEmoji(CodePoints.toString(0x1F49B), listOf("yellow_heart"), 28, 11),
    FacebookEmoji(CodePoints.toString(0x1F49A), listOf("green_heart"), 28, 10),
    FacebookEmoji(CodePoints.toString(0x1F499), listOf("blue_heart"), 28, 9),
    FacebookEmoji(CodePoints.toString(0x1FA75), listOf("light_blue_heart"), 54, 55),
    FacebookEmoji(CodePoints.toString(0x1F49C), listOf("purple_heart"), 28, 12),
    FacebookEmoji(CodePoints.toString(0x1F90E), listOf("brown_heart"), 39, 30),
    FacebookEmoji(CodePoints.toString(0x1F5A4), listOf("black_heart"), 32, 20),
    FacebookEmoji(CodePoints.toString(0x1FA76), listOf("grey_heart"), 54, 56),
    FacebookEmoji(CodePoints.toString(0x1F90D), listOf("white_heart"), 39, 29),
    FacebookEmoji(CodePoints.toString(0x1F48B), listOf("kiss"), 27, 7),
    FacebookEmoji(CodePoints.toString(0x1F4AF), listOf("100"), 28, 36),
    FacebookEmoji(CodePoints.toString(0x1F4A2), listOf("anger"), 28, 18),
    FacebookEmoji(CodePoints.toString(0x1F4A5), listOf("boom", "collision"), 28, 21),
    FacebookEmoji(CodePoints.toString(0x1F4AB), listOf("dizzy"), 28, 32),
    FacebookEmoji(CodePoints.toString(0x1F4A6), listOf("sweat_drops"), 28, 22),
    FacebookEmoji(CodePoints.toString(0x1F4A8), listOf("dash"), 28, 24),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1F573),
      shortcodes = listOf("hole"),
      x = 31,
      y = 24,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1F573, 0xFE0F), emptyList(), 31, 24),
      ),
    ),
    FacebookEmoji(CodePoints.toString(0x1F4AC), listOf("speech_balloon"), 28, 33),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1F5E8),
      shortcodes = listOf("left_speech_bubble"),
      x = 32,
      y = 37,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1F5E8, 0xFE0F), emptyList(), 32, 37),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1F5EF),
      shortcodes = listOf("right_anger_bubble"),
      x = 32,
      y = 38,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1F5EF, 0xFE0F), emptyList(), 32, 38),
      ),
    ),
    FacebookEmoji(CodePoints.toString(0x1F4AD), listOf("thought_balloon"), 28, 34),
    FacebookEmoji(CodePoints.toString(0x1F4A4), listOf("zzz"), 28, 20),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1F44B),
      shortcodes = listOf("wave"),
      x = 12,
      y = 48,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1F44B, 0x1F3FB), emptyList(), 12, 49),
        FacebookEmoji(CodePoints.toString(0x1F44B, 0x1F3FC), emptyList(), 12, 50),
        FacebookEmoji(CodePoints.toString(0x1F44B, 0x1F3FD), emptyList(), 12, 51),
        FacebookEmoji(CodePoints.toString(0x1F44B, 0x1F3FE), emptyList(), 12, 52),
        FacebookEmoji(CodePoints.toString(0x1F44B, 0x1F3FF), emptyList(), 12, 53),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1F91A),
      shortcodes = listOf("raised_back_of_hand"),
      x = 39,
      y = 57,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1F91A, 0x1F3FB), emptyList(), 39, 58),
        FacebookEmoji(CodePoints.toString(0x1F91A, 0x1F3FC), emptyList(), 39, 59),
        FacebookEmoji(CodePoints.toString(0x1F91A, 0x1F3FD), emptyList(), 39, 60),
        FacebookEmoji(CodePoints.toString(0x1F91A, 0x1F3FE), emptyList(), 39, 61),
        FacebookEmoji(CodePoints.toString(0x1F91A, 0x1F3FF), emptyList(), 40, 0),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1F590, 0xFE0F),
      shortcodes = listOf("raised_hand_with_fingers_splayed"),
      x = 32,
      y = 2,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1F590, 0x1F3FB), emptyList(), 32, 3),
        FacebookEmoji(CodePoints.toString(0x1F590, 0x1F3FC), emptyList(), 32, 4),
        FacebookEmoji(CodePoints.toString(0x1F590, 0x1F3FD), emptyList(), 32, 5),
        FacebookEmoji(CodePoints.toString(0x1F590, 0x1F3FE), emptyList(), 32, 6),
        FacebookEmoji(CodePoints.toString(0x1F590, 0x1F3FF), emptyList(), 32, 7),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x270B),
      shortcodes = listOf("hand", "raised_hand"),
      x = 60,
      y = 0,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x270B, 0x1F3FB), emptyList(), 60, 1),
        FacebookEmoji(CodePoints.toString(0x270B, 0x1F3FC), emptyList(), 60, 2),
        FacebookEmoji(CodePoints.toString(0x270B, 0x1F3FD), emptyList(), 60, 3),
        FacebookEmoji(CodePoints.toString(0x270B, 0x1F3FE), emptyList(), 60, 4),
        FacebookEmoji(CodePoints.toString(0x270B, 0x1F3FF), emptyList(), 60, 5),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1F596),
      shortcodes = listOf("spock-hand"),
      x = 32,
      y = 14,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1F596, 0x1F3FB), emptyList(), 32, 15),
        FacebookEmoji(CodePoints.toString(0x1F596, 0x1F3FC), emptyList(), 32, 16),
        FacebookEmoji(CodePoints.toString(0x1F596, 0x1F3FD), emptyList(), 32, 17),
        FacebookEmoji(CodePoints.toString(0x1F596, 0x1F3FE), emptyList(), 32, 18),
        FacebookEmoji(CodePoints.toString(0x1F596, 0x1F3FF), emptyList(), 32, 19),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1FAF1),
      shortcodes = listOf("rightwards_hand"),
      x = 56,
      y = 45,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1FAF1, 0x1F3FB), emptyList(), 56, 46),
        FacebookEmoji(CodePoints.toString(0x1FAF1, 0x1F3FC), emptyList(), 56, 47),
        FacebookEmoji(CodePoints.toString(0x1FAF1, 0x1F3FD), emptyList(), 56, 48),
        FacebookEmoji(CodePoints.toString(0x1FAF1, 0x1F3FE), emptyList(), 56, 49),
        FacebookEmoji(CodePoints.toString(0x1FAF1, 0x1F3FF), emptyList(), 56, 50),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1FAF2),
      shortcodes = listOf("leftwards_hand"),
      x = 56,
      y = 51,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1FAF2, 0x1F3FB), emptyList(), 56, 52),
        FacebookEmoji(CodePoints.toString(0x1FAF2, 0x1F3FC), emptyList(), 56, 53),
        FacebookEmoji(CodePoints.toString(0x1FAF2, 0x1F3FD), emptyList(), 56, 54),
        FacebookEmoji(CodePoints.toString(0x1FAF2, 0x1F3FE), emptyList(), 56, 55),
        FacebookEmoji(CodePoints.toString(0x1FAF2, 0x1F3FF), emptyList(), 56, 56),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1FAF3),
      shortcodes = listOf("palm_down_hand"),
      x = 56,
      y = 57,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1FAF3, 0x1F3FB), emptyList(), 56, 58),
        FacebookEmoji(CodePoints.toString(0x1FAF3, 0x1F3FC), emptyList(), 56, 59),
        FacebookEmoji(CodePoints.toString(0x1FAF3, 0x1F3FD), emptyList(), 56, 60),
        FacebookEmoji(CodePoints.toString(0x1FAF3, 0x1F3FE), emptyList(), 56, 61),
        FacebookEmoji(CodePoints.toString(0x1FAF3, 0x1F3FF), emptyList(), 57, 0),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1FAF4),
      shortcodes = listOf("palm_up_hand"),
      x = 57,
      y = 1,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1FAF4, 0x1F3FB), emptyList(), 57, 2),
        FacebookEmoji(CodePoints.toString(0x1FAF4, 0x1F3FC), emptyList(), 57, 3),
        FacebookEmoji(CodePoints.toString(0x1FAF4, 0x1F3FD), emptyList(), 57, 4),
        FacebookEmoji(CodePoints.toString(0x1FAF4, 0x1F3FE), emptyList(), 57, 5),
        FacebookEmoji(CodePoints.toString(0x1FAF4, 0x1F3FF), emptyList(), 57, 6),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1FAF7),
      shortcodes = listOf("leftwards_pushing_hand"),
      x = 57,
      y = 19,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1FAF7, 0x1F3FB), emptyList(), 57, 20),
        FacebookEmoji(CodePoints.toString(0x1FAF7, 0x1F3FC), emptyList(), 57, 21),
        FacebookEmoji(CodePoints.toString(0x1FAF7, 0x1F3FD), emptyList(), 57, 22),
        FacebookEmoji(CodePoints.toString(0x1FAF7, 0x1F3FE), emptyList(), 57, 23),
        FacebookEmoji(CodePoints.toString(0x1FAF7, 0x1F3FF), emptyList(), 57, 24),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1FAF8),
      shortcodes = listOf("rightwards_pushing_hand"),
      x = 57,
      y = 25,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1FAF8, 0x1F3FB), emptyList(), 57, 26),
        FacebookEmoji(CodePoints.toString(0x1FAF8, 0x1F3FC), emptyList(), 57, 27),
        FacebookEmoji(CodePoints.toString(0x1FAF8, 0x1F3FD), emptyList(), 57, 28),
        FacebookEmoji(CodePoints.toString(0x1FAF8, 0x1F3FE), emptyList(), 57, 29),
        FacebookEmoji(CodePoints.toString(0x1FAF8, 0x1F3FF), emptyList(), 57, 30),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1F44C),
      shortcodes = listOf("ok_hand"),
      x = 12,
      y = 54,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1F44C, 0x1F3FB), emptyList(), 12, 55),
        FacebookEmoji(CodePoints.toString(0x1F44C, 0x1F3FC), emptyList(), 12, 56),
        FacebookEmoji(CodePoints.toString(0x1F44C, 0x1F3FD), emptyList(), 12, 57),
        FacebookEmoji(CodePoints.toString(0x1F44C, 0x1F3FE), emptyList(), 12, 58),
        FacebookEmoji(CodePoints.toString(0x1F44C, 0x1F3FF), emptyList(), 12, 59),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1F90C),
      shortcodes = listOf("pinched_fingers"),
      x = 39,
      y = 23,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1F90C, 0x1F3FB), emptyList(), 39, 24),
        FacebookEmoji(CodePoints.toString(0x1F90C, 0x1F3FC), emptyList(), 39, 25),
        FacebookEmoji(CodePoints.toString(0x1F90C, 0x1F3FD), emptyList(), 39, 26),
        FacebookEmoji(CodePoints.toString(0x1F90C, 0x1F3FE), emptyList(), 39, 27),
        FacebookEmoji(CodePoints.toString(0x1F90C, 0x1F3FF), emptyList(), 39, 28),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1F90F),
      shortcodes = listOf("pinching_hand"),
      x = 39,
      y = 31,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1F90F, 0x1F3FB), emptyList(), 39, 32),
        FacebookEmoji(CodePoints.toString(0x1F90F, 0x1F3FC), emptyList(), 39, 33),
        FacebookEmoji(CodePoints.toString(0x1F90F, 0x1F3FD), emptyList(), 39, 34),
        FacebookEmoji(CodePoints.toString(0x1F90F, 0x1F3FE), emptyList(), 39, 35),
        FacebookEmoji(CodePoints.toString(0x1F90F, 0x1F3FF), emptyList(), 39, 36),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x270C, 0xFE0F),
      shortcodes = listOf("v"),
      x = 60,
      y = 6,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x270C, 0x1F3FB), emptyList(), 60, 7),
        FacebookEmoji(CodePoints.toString(0x270C, 0x1F3FC), emptyList(), 60, 8),
        FacebookEmoji(CodePoints.toString(0x270C, 0x1F3FD), emptyList(), 60, 9),
        FacebookEmoji(CodePoints.toString(0x270C, 0x1F3FE), emptyList(), 60, 10),
        FacebookEmoji(CodePoints.toString(0x270C, 0x1F3FF), emptyList(), 60, 11),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1F91E),
      shortcodes = listOf("crossed_fingers", "hand_with_index_and_middle_fingers_crossed"),
      x = 40,
      y = 39,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1F91E, 0x1F3FB), emptyList(), 40, 40),
        FacebookEmoji(CodePoints.toString(0x1F91E, 0x1F3FC), emptyList(), 40, 41),
        FacebookEmoji(CodePoints.toString(0x1F91E, 0x1F3FD), emptyList(), 40, 42),
        FacebookEmoji(CodePoints.toString(0x1F91E, 0x1F3FE), emptyList(), 40, 43),
        FacebookEmoji(CodePoints.toString(0x1F91E, 0x1F3FF), emptyList(), 40, 44),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1FAF0),
      shortcodes = listOf("hand_with_index_finger_and_thumb_crossed"),
      x = 56,
      y = 39,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1FAF0, 0x1F3FB), emptyList(), 56, 40),
        FacebookEmoji(CodePoints.toString(0x1FAF0, 0x1F3FC), emptyList(), 56, 41),
        FacebookEmoji(CodePoints.toString(0x1FAF0, 0x1F3FD), emptyList(), 56, 42),
        FacebookEmoji(CodePoints.toString(0x1FAF0, 0x1F3FE), emptyList(), 56, 43),
        FacebookEmoji(CodePoints.toString(0x1FAF0, 0x1F3FF), emptyList(), 56, 44),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1F91F),
      shortcodes = listOf("i_love_you_hand_sign"),
      x = 40,
      y = 45,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1F91F, 0x1F3FB), emptyList(), 40, 46),
        FacebookEmoji(CodePoints.toString(0x1F91F, 0x1F3FC), emptyList(), 40, 47),
        FacebookEmoji(CodePoints.toString(0x1F91F, 0x1F3FD), emptyList(), 40, 48),
        FacebookEmoji(CodePoints.toString(0x1F91F, 0x1F3FE), emptyList(), 40, 49),
        FacebookEmoji(CodePoints.toString(0x1F91F, 0x1F3FF), emptyList(), 40, 50),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1F918),
      shortcodes = listOf("the_horns", "sign_of_the_horns"),
      x = 39,
      y = 45,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1F918, 0x1F3FB), emptyList(), 39, 46),
        FacebookEmoji(CodePoints.toString(0x1F918, 0x1F3FC), emptyList(), 39, 47),
        FacebookEmoji(CodePoints.toString(0x1F918, 0x1F3FD), emptyList(), 39, 48),
        FacebookEmoji(CodePoints.toString(0x1F918, 0x1F3FE), emptyList(), 39, 49),
        FacebookEmoji(CodePoints.toString(0x1F918, 0x1F3FF), emptyList(), 39, 50),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1F919),
      shortcodes = listOf("call_me_hand"),
      x = 39,
      y = 51,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1F919, 0x1F3FB), emptyList(), 39, 52),
        FacebookEmoji(CodePoints.toString(0x1F919, 0x1F3FC), emptyList(), 39, 53),
        FacebookEmoji(CodePoints.toString(0x1F919, 0x1F3FD), emptyList(), 39, 54),
        FacebookEmoji(CodePoints.toString(0x1F919, 0x1F3FE), emptyList(), 39, 55),
        FacebookEmoji(CodePoints.toString(0x1F919, 0x1F3FF), emptyList(), 39, 56),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1F448),
      shortcodes = listOf("point_left"),
      x = 12,
      y = 30,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1F448, 0x1F3FB), emptyList(), 12, 31),
        FacebookEmoji(CodePoints.toString(0x1F448, 0x1F3FC), emptyList(), 12, 32),
        FacebookEmoji(CodePoints.toString(0x1F448, 0x1F3FD), emptyList(), 12, 33),
        FacebookEmoji(CodePoints.toString(0x1F448, 0x1F3FE), emptyList(), 12, 34),
        FacebookEmoji(CodePoints.toString(0x1F448, 0x1F3FF), emptyList(), 12, 35),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1F449),
      shortcodes = listOf("point_right"),
      x = 12,
      y = 36,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1F449, 0x1F3FB), emptyList(), 12, 37),
        FacebookEmoji(CodePoints.toString(0x1F449, 0x1F3FC), emptyList(), 12, 38),
        FacebookEmoji(CodePoints.toString(0x1F449, 0x1F3FD), emptyList(), 12, 39),
        FacebookEmoji(CodePoints.toString(0x1F449, 0x1F3FE), emptyList(), 12, 40),
        FacebookEmoji(CodePoints.toString(0x1F449, 0x1F3FF), emptyList(), 12, 41),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1F446),
      shortcodes = listOf("point_up_2"),
      x = 12,
      y = 18,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1F446, 0x1F3FB), emptyList(), 12, 19),
        FacebookEmoji(CodePoints.toString(0x1F446, 0x1F3FC), emptyList(), 12, 20),
        FacebookEmoji(CodePoints.toString(0x1F446, 0x1F3FD), emptyList(), 12, 21),
        FacebookEmoji(CodePoints.toString(0x1F446, 0x1F3FE), emptyList(), 12, 22),
        FacebookEmoji(CodePoints.toString(0x1F446, 0x1F3FF), emptyList(), 12, 23),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1F595),
      shortcodes = listOf("middle_finger", "reversed_hand_with_middle_finger_extended"),
      x = 32,
      y = 8,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1F595, 0x1F3FB), emptyList(), 32, 9),
        FacebookEmoji(CodePoints.toString(0x1F595, 0x1F3FC), emptyList(), 32, 10),
        FacebookEmoji(CodePoints.toString(0x1F595, 0x1F3FD), emptyList(), 32, 11),
        FacebookEmoji(CodePoints.toString(0x1F595, 0x1F3FE), emptyList(), 32, 12),
        FacebookEmoji(CodePoints.toString(0x1F595, 0x1F3FF), emptyList(), 32, 13),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1F447),
      shortcodes = listOf("point_down"),
      x = 12,
      y = 24,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1F447, 0x1F3FB), emptyList(), 12, 25),
        FacebookEmoji(CodePoints.toString(0x1F447, 0x1F3FC), emptyList(), 12, 26),
        FacebookEmoji(CodePoints.toString(0x1F447, 0x1F3FD), emptyList(), 12, 27),
        FacebookEmoji(CodePoints.toString(0x1F447, 0x1F3FE), emptyList(), 12, 28),
        FacebookEmoji(CodePoints.toString(0x1F447, 0x1F3FF), emptyList(), 12, 29),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x261D, 0xFE0F),
      shortcodes = listOf("point_up"),
      x = 58,
      y = 18,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x261D, 0x1F3FB), emptyList(), 58, 19),
        FacebookEmoji(CodePoints.toString(0x261D, 0x1F3FC), emptyList(), 58, 20),
        FacebookEmoji(CodePoints.toString(0x261D, 0x1F3FD), emptyList(), 58, 21),
        FacebookEmoji(CodePoints.toString(0x261D, 0x1F3FE), emptyList(), 58, 22),
        FacebookEmoji(CodePoints.toString(0x261D, 0x1F3FF), emptyList(), 58, 23),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1FAF5),
      shortcodes = listOf("index_pointing_at_the_viewer"),
      x = 57,
      y = 7,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1FAF5, 0x1F3FB), emptyList(), 57, 8),
        FacebookEmoji(CodePoints.toString(0x1FAF5, 0x1F3FC), emptyList(), 57, 9),
        FacebookEmoji(CodePoints.toString(0x1FAF5, 0x1F3FD), emptyList(), 57, 10),
        FacebookEmoji(CodePoints.toString(0x1FAF5, 0x1F3FE), emptyList(), 57, 11),
        FacebookEmoji(CodePoints.toString(0x1FAF5, 0x1F3FF), emptyList(), 57, 12),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1F44D),
      shortcodes = listOf("+1", "thumbsup"),
      x = 12,
      y = 60,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1F44D, 0x1F3FB), emptyList(), 12, 61),
        FacebookEmoji(CodePoints.toString(0x1F44D, 0x1F3FC), emptyList(), 13, 0),
        FacebookEmoji(CodePoints.toString(0x1F44D, 0x1F3FD), emptyList(), 13, 1),
        FacebookEmoji(CodePoints.toString(0x1F44D, 0x1F3FE), emptyList(), 13, 2),
        FacebookEmoji(CodePoints.toString(0x1F44D, 0x1F3FF), emptyList(), 13, 3),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1F44E),
      shortcodes = listOf("-1", "thumbsdown"),
      x = 13,
      y = 4,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1F44E, 0x1F3FB), emptyList(), 13, 5),
        FacebookEmoji(CodePoints.toString(0x1F44E, 0x1F3FC), emptyList(), 13, 6),
        FacebookEmoji(CodePoints.toString(0x1F44E, 0x1F3FD), emptyList(), 13, 7),
        FacebookEmoji(CodePoints.toString(0x1F44E, 0x1F3FE), emptyList(), 13, 8),
        FacebookEmoji(CodePoints.toString(0x1F44E, 0x1F3FF), emptyList(), 13, 9),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x270A),
      shortcodes = listOf("fist"),
      x = 59,
      y = 56,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x270A, 0x1F3FB), emptyList(), 59, 57),
        FacebookEmoji(CodePoints.toString(0x270A, 0x1F3FC), emptyList(), 59, 58),
        FacebookEmoji(CodePoints.toString(0x270A, 0x1F3FD), emptyList(), 59, 59),
        FacebookEmoji(CodePoints.toString(0x270A, 0x1F3FE), emptyList(), 59, 60),
        FacebookEmoji(CodePoints.toString(0x270A, 0x1F3FF), emptyList(), 59, 61),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1F44A),
      shortcodes = listOf("facepunch", "punch"),
      x = 12,
      y = 42,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1F44A, 0x1F3FB), emptyList(), 12, 43),
        FacebookEmoji(CodePoints.toString(0x1F44A, 0x1F3FC), emptyList(), 12, 44),
        FacebookEmoji(CodePoints.toString(0x1F44A, 0x1F3FD), emptyList(), 12, 45),
        FacebookEmoji(CodePoints.toString(0x1F44A, 0x1F3FE), emptyList(), 12, 46),
        FacebookEmoji(CodePoints.toString(0x1F44A, 0x1F3FF), emptyList(), 12, 47),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1F91B),
      shortcodes = listOf("left-facing_fist"),
      x = 40,
      y = 1,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1F91B, 0x1F3FB), emptyList(), 40, 2),
        FacebookEmoji(CodePoints.toString(0x1F91B, 0x1F3FC), emptyList(), 40, 3),
        FacebookEmoji(CodePoints.toString(0x1F91B, 0x1F3FD), emptyList(), 40, 4),
        FacebookEmoji(CodePoints.toString(0x1F91B, 0x1F3FE), emptyList(), 40, 5),
        FacebookEmoji(CodePoints.toString(0x1F91B, 0x1F3FF), emptyList(), 40, 6),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1F91C),
      shortcodes = listOf("right-facing_fist"),
      x = 40,
      y = 7,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1F91C, 0x1F3FB), emptyList(), 40, 8),
        FacebookEmoji(CodePoints.toString(0x1F91C, 0x1F3FC), emptyList(), 40, 9),
        FacebookEmoji(CodePoints.toString(0x1F91C, 0x1F3FD), emptyList(), 40, 10),
        FacebookEmoji(CodePoints.toString(0x1F91C, 0x1F3FE), emptyList(), 40, 11),
        FacebookEmoji(CodePoints.toString(0x1F91C, 0x1F3FF), emptyList(), 40, 12),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1F44F),
      shortcodes = listOf("clap"),
      x = 13,
      y = 10,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1F44F, 0x1F3FB), emptyList(), 13, 11),
        FacebookEmoji(CodePoints.toString(0x1F44F, 0x1F3FC), emptyList(), 13, 12),
        FacebookEmoji(CodePoints.toString(0x1F44F, 0x1F3FD), emptyList(), 13, 13),
        FacebookEmoji(CodePoints.toString(0x1F44F, 0x1F3FE), emptyList(), 13, 14),
        FacebookEmoji(CodePoints.toString(0x1F44F, 0x1F3FF), emptyList(), 13, 15),
      ),
    ),
    FacebookEmoji(
      unicode = CodePoints.toString(0x1F64C),
      shortcodes = listOf("raised_hands"),
      x = 35,
      y = 9,
      variants = listOf(
        FacebookEmoji(CodePoints.toString(0x1F64C, 0x1F3FB), emptyList(), 35, 10),
        FacebookEmoji(CodePoints.toString(0x1F64C, 0x1F3FC), emptyList(), 35, 11),
        FacebookEmoji(CodePoints.toString(0x1F64C, 0x1F3FD), emptyList(), 35, 12),
        FacebookEmoji(CodePoints.toString(0x1F64C, 0x1F3FE), emptyList(), 35, 13),
        FacebookEmoji(CodePoints.toString(0x1F64C, 0x1F3FF), emptyList(), 35, 14),
      ),
    ),
  )
}
