/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vanniktech.emoji.androidxemoji2.category

import com.vanniktech.emoji.androidxemoji2.AndroidxEmoji2
import de.cketti.codepoints.CodePoints

internal object FlagsCategoryChunk1 {
  internal val EMOJIS: List<AndroidxEmoji2> = listOf(
    AndroidxEmoji2(CodePoints.toString(0x1F1EC, 0x1F1F6), listOf("flag-gq")),
    AndroidxEmoji2(CodePoints.toString(0x1F1EC, 0x1F1F7), listOf("flag-gr")),
    AndroidxEmoji2(CodePoints.toString(0x1F1EC, 0x1F1F8), listOf("flag-gs")),
    AndroidxEmoji2(CodePoints.toString(0x1F1EC, 0x1F1F9), listOf("flag-gt")),
    AndroidxEmoji2(CodePoints.toString(0x1F1EC, 0x1F1FA), listOf("flag-gu")),
    AndroidxEmoji2(CodePoints.toString(0x1F1EC, 0x1F1FC), listOf("flag-gw")),
    AndroidxEmoji2(CodePoints.toString(0x1F1EC, 0x1F1FE), listOf("flag-gy")),
    AndroidxEmoji2(CodePoints.toString(0x1F1ED, 0x1F1F0), listOf("flag-hk")),
    AndroidxEmoji2(CodePoints.toString(0x1F1ED, 0x1F1F2), listOf("flag-hm")),
    AndroidxEmoji2(CodePoints.toString(0x1F1ED, 0x1F1F3), listOf("flag-hn")),
    AndroidxEmoji2(CodePoints.toString(0x1F1ED, 0x1F1F7), listOf("flag-hr")),
    AndroidxEmoji2(CodePoints.toString(0x1F1ED, 0x1F1F9), listOf("flag-ht")),
    AndroidxEmoji2(CodePoints.toString(0x1F1ED, 0x1F1FA), listOf("flag-hu")),
    AndroidxEmoji2(CodePoints.toString(0x1F1EE, 0x1F1E8), listOf("flag-ic")),
    AndroidxEmoji2(CodePoints.toString(0x1F1EE, 0x1F1E9), listOf("flag-id")),
    AndroidxEmoji2(CodePoints.toString(0x1F1EE, 0x1F1EA), listOf("flag-ie")),
    AndroidxEmoji2(CodePoints.toString(0x1F1EE, 0x1F1F1), listOf("flag-il")),
    AndroidxEmoji2(CodePoints.toString(0x1F1EE, 0x1F1F2), listOf("flag-im")),
    AndroidxEmoji2(CodePoints.toString(0x1F1EE, 0x1F1F3), listOf("flag-in")),
    AndroidxEmoji2(CodePoints.toString(0x1F1EE, 0x1F1F4), listOf("flag-io")),
    AndroidxEmoji2(CodePoints.toString(0x1F1EE, 0x1F1F6), listOf("flag-iq")),
    AndroidxEmoji2(CodePoints.toString(0x1F1EE, 0x1F1F7), listOf("flag-ir")),
    AndroidxEmoji2(CodePoints.toString(0x1F1EE, 0x1F1F8), listOf("flag-is")),
    AndroidxEmoji2(CodePoints.toString(0x1F1EE, 0x1F1F9), listOf("it", "flag-it")),
    AndroidxEmoji2(CodePoints.toString(0x1F1EF, 0x1F1EA), listOf("flag-je")),
    AndroidxEmoji2(CodePoints.toString(0x1F1EF, 0x1F1F2), listOf("flag-jm")),
    AndroidxEmoji2(CodePoints.toString(0x1F1EF, 0x1F1F4), listOf("flag-jo")),
    AndroidxEmoji2(CodePoints.toString(0x1F1EF, 0x1F1F5), listOf("jp", "flag-jp")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F0, 0x1F1EA), listOf("flag-ke")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F0, 0x1F1EC), listOf("flag-kg")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F0, 0x1F1ED), listOf("flag-kh")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F0, 0x1F1EE), listOf("flag-ki")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F0, 0x1F1F2), listOf("flag-km")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F0, 0x1F1F3), listOf("flag-kn")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F0, 0x1F1F5), listOf("flag-kp")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F0, 0x1F1F7), listOf("kr", "flag-kr")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F0, 0x1F1FC), listOf("flag-kw")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F0, 0x1F1FE), listOf("flag-ky")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F0, 0x1F1FF), listOf("flag-kz")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F1, 0x1F1E6), listOf("flag-la")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F1, 0x1F1E7), listOf("flag-lb")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F1, 0x1F1E8), listOf("flag-lc")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F1, 0x1F1EE), listOf("flag-li")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F1, 0x1F1F0), listOf("flag-lk")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F1, 0x1F1F7), listOf("flag-lr")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F1, 0x1F1F8), listOf("flag-ls")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F1, 0x1F1F9), listOf("flag-lt")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F1, 0x1F1FA), listOf("flag-lu")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F1, 0x1F1FB), listOf("flag-lv")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F1, 0x1F1FE), listOf("flag-ly")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F2, 0x1F1E6), listOf("flag-ma")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F2, 0x1F1E8), listOf("flag-mc")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F2, 0x1F1E9), listOf("flag-md")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F2, 0x1F1EA), listOf("flag-me")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F2, 0x1F1EB), listOf("flag-mf")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F2, 0x1F1EC), listOf("flag-mg")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F2, 0x1F1ED), listOf("flag-mh")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F2, 0x1F1F0), listOf("flag-mk")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F2, 0x1F1F1), listOf("flag-ml")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F2, 0x1F1F2), listOf("flag-mm")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F2, 0x1F1F3), listOf("flag-mn")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F2, 0x1F1F4), listOf("flag-mo")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F2, 0x1F1F5), listOf("flag-mp")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F2, 0x1F1F6), listOf("flag-mq")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F2, 0x1F1F7), listOf("flag-mr")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F2, 0x1F1F8), listOf("flag-ms")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F2, 0x1F1F9), listOf("flag-mt")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F2, 0x1F1FA), listOf("flag-mu")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F2, 0x1F1FB), listOf("flag-mv")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F2, 0x1F1FC), listOf("flag-mw")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F2, 0x1F1FD), listOf("flag-mx")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F2, 0x1F1FE), listOf("flag-my")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F2, 0x1F1FF), listOf("flag-mz")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F3, 0x1F1E6), listOf("flag-na")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F3, 0x1F1E8), listOf("flag-nc")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F3, 0x1F1EA), listOf("flag-ne")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F3, 0x1F1EB), listOf("flag-nf")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F3, 0x1F1EC), listOf("flag-ng")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F3, 0x1F1EE), listOf("flag-ni")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F3, 0x1F1F1), listOf("flag-nl")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F3, 0x1F1F4), listOf("flag-no")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F3, 0x1F1F5), listOf("flag-np")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F3, 0x1F1F7), listOf("flag-nr")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F3, 0x1F1FA), listOf("flag-nu")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F3, 0x1F1FF), listOf("flag-nz")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F4, 0x1F1F2), listOf("flag-om")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F5, 0x1F1E6), listOf("flag-pa")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F5, 0x1F1EA), listOf("flag-pe")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F5, 0x1F1EB), listOf("flag-pf")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F5, 0x1F1EC), listOf("flag-pg")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F5, 0x1F1ED), listOf("flag-ph")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F5, 0x1F1F0), listOf("flag-pk")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F5, 0x1F1F1), listOf("flag-pl")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F5, 0x1F1F2), listOf("flag-pm")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F5, 0x1F1F3), listOf("flag-pn")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F5, 0x1F1F7), listOf("flag-pr")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F5, 0x1F1F8), listOf("flag-ps")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F5, 0x1F1F9), listOf("flag-pt")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F5, 0x1F1FC), listOf("flag-pw")),
    AndroidxEmoji2(CodePoints.toString(0x1F1F5, 0x1F1FE), listOf("flag-py")),
  )
}
